### ISSUE TITLE
failed to load external entity "xsltproc"

### ISSUE THREAD

**Issue by hguiney** [andybluntish/grunt-xsltproc#13]
Tested on Windows 7 x64, and Linux (CentOS 6.5) x64, with xsltproc installed to my PATH:

> Running "xsltproc:svg2symbol" (xsltproc) task
> warning: failed to load external entity "xsltproc"
> cannot parse xsltproc
> Warning: warning: failed to load external entity "xsltproc"
> cannot parse xsltproc Use --force to continue.

The bare command `xsltproc foo.xslt bar.xml` works fine, but not the Grunt task. My config:

    xsltproc: {
      options: {
        stylesheet: '<%= config.app %>/assets/svg2symbol.xslt'
      },
      svg2symbol: {
        files: [{
          expand: true,
          cwd: '<%= config.app %>/assets/img',
          src: '*.svg',
          dest: '<%= build_dir %>/assets/img',
          ext: '.symbol.svg'
        }]
      }
    },

**Comment by andybluntish** [comment]
G'day Hugh,

Unfortunately I don't have access to test on Windows 7 or CentOS so I'm afraid I may not be able to be too much help. I would check that the value of `build_dir` in the target configuration is set (did you mean `config.build_dir`).

Also, ensure that you are not outputting into the same directory as you are input files (the config you had in the other issue (#14) you opened was doing just that), otherwise you will run into trouble the second time you run the task. The task generates the output file first to ensure the path exists before handing things off to `xsltproc`. So if your `src` and `dest` directories are the same, the second time the task is run it will overwrite your `*.symbol.svg` files with an empty file, but then try to pass that to `xsltproc`, which I believe is what is causing the error.

I'm sorry that I can't say for sure if this is the problem, but I hope it helps.

Cheers.
